/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testAppReturnHelloWorld(){
      App classUnderTest = new App();
      assertEquals("Hello World!", classUnderTest.getGreeting());
    }

    @Test
    public void testAppHasSumAverage(){
      App classUnderTest = new App();
      assertNotNull("app should have results of summary and average", classUnderTest.getResultSumAverage(2,3));
    }

    @Test
    public void testAppHasSumToAverage(){
      App classUnderTest = new App();
      assertNotNull("app should have results of summary(to) and average", classUnderTest.getResultSumToAverage(1,10));
    }

    @Test
    public void testAppHasOddEven(){
      App classUnderTest = new App();
      assertNotNull("app should have results of odd and even", classUnderTest.getResultOddEven(1,10));
    }
}
